spring.application.name=projetolistacompras
debug=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

server.port=8080


spring.security.user.name=disable
spring.security.user.password=disable   



projeto.jwtSecret=JXQZKL/UAyLjeKRXXbMS48RM3SrLA8toKEB5q9/33TEGqhOuWYWqtn6u/C/30GmSEbpN1N3xn44RdUuxR6Q4jA==
projeto.jwtExpirationMs=900000 

spring.datasource.url=jdbc:postgresql://db.dgipjspmscmswupxtexu.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=ntwjy8CgJhMM2VHK


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

openai.api.key=${OPENAI_API_KEY:}